### ISSUE TITLE
Disclamer for other people, fix steam library

### ISSUE THREAD

**Issue by TheCodeLamp** [Omni-guides/Wabbajack-Modlist-Linux#31] opened 2024-12-29 12:49 UTC
This isn't an issue with this guide or the scripts. But wanted to let people know that if you add a steam library from the steam gui it might add it like `/run/host/**/library` you need to remove the `/run/host` part for it to work properly and fix any flatpak issues if they arrise.
The `/run/host` can be removed by manually editing your `~/.local/share/Steam/steamapps/libraryfolders.vdf` file.

**Comment by TheCodeLamp** [comment] 2024-12-29 13:32
Ok, after doing further trials, this doesn't seem to work. Launching wabbajack through steam doesn't give it permission to see the other steam library paths no matter what prefixes or workarounds I do.

**Comment by Omni-guides** [comment] 2024-12-29 13:50
I must admit, I do forget some people use the flatpak version of Steam for whatever reason..

I'll try to incorporate this into a future version of the script.

**Comment by TheCodeLamp** [comment] 2024-12-30 11:35
This was a issue with the protontricks flatpak. I do indeed have steam installed at system level. Still, for some reason steam doesn't give wabbajack visibility for my other steam libraries. In the wabbajack log file it says that my `/var/games/shared/SteamLibrary` doesn't exist, even though Wabbajack is installed at `/var/games/shared/Wabbajack`. If I launch Wabbajack though the wine script it reads the library correctly, but it crashes as soon as it loads.

**Comment by TheCodeLamp** [comment] 2024-12-30 11:48
Ok, I found a fix for wabbajack not seeing my folders. You need to add your other library folders to the envvar `PRESSURE_VESSEL_FILESYSTEMS_RW` before you launch steam. This will make them visible inside the proton container. Also needs the removal of `/run/host` as mentioned before.
See this wiki: https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#sharing-directories-with-the-container

**Comment by Omni-guides** [comment] 2024-12-30 14:05
What is odd for me though is, I have never come across any system or distro where the Steam install that uses /run/host as a path for it's library. What is different about your set up?

Just trying to gauge if this is a one-off situation because you have an abnormal set up in some way, or if it's something that may be more wide spread and I should look into trying to handle it in the script.

**Comment by TheCodeLamp** [comment] 2024-12-30 14:09
I use bazzite, but as steam is installed on machine I don't think that makes much difference. Steam has worked fine with the `/run/host` prefix for almost a year now, so I don't remember how I set it up.

**Comment by SulfurNitride** [comment] 2024-12-31 11:53
I just tested it with the script and it worked just fine, so im not sure what happened on your end.

**Comment by TheCodeLamp** [comment] 2024-12-31 15:20
I should clarify. This is a problem with the fact that steam uses a similar containerization system as flatpak. If you have installed protontricks as a flatpak, additional libraries can't have the `/run/host` prefix to be seen. Both flatpak and steam's own containerization uses this path for internal use and will not be able to see each other's paths even if given access through flatseal.

**Comment by Omni-guides** [comment] 2024-12-31 15:27
That is true, but can be easily overcome by managing the flatpak permissions for the protontricks app either via flatseal or simply by using the command line, e.g.

`flatpak override --user --filesystem=/strage/path/to/SteamLibrary com.github.Matoking.protontricks`

This is persistent across reboots. Flatseal can be used to manage flatpak permissions via a gui interface if you prefer.

Anyway, I've had a look at documentation, and Sulfur confirmed via a new Bazzite VM that /run/host mount/path is not 'standard' for a Bazzite install.

That's not to say that your set up isn't usable for you, just that it's abnormal enough that I'm not likely to add handling of /run/host pathing to the script. The main thing is you got it running, so I think we're fine to close this?

**Comment by TheCodeLamp** [comment] 2024-12-31 15:37
The `/run/host` path is reserved by flatpak for it's own use. Read the [sandbox permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html) and look at the section relating to filesystem access:
"Access to `/home`, `/media`, `/opt`, `/run/media`, `/srv` and everything provided by host-os, host-etc mounted in `/run/host`"

If I have my steam library set to `/run/host/var/games/shared/SteamLibrary` and run `protontricks -l` (Remember, protontricks is installed through flatpak) I get this error:
```bash
protontricks (WARNING): Protontricks does not appear to have access to the following directories:
 /run/host/var/games/shared/SteamLibrary

To fix this problem, grant access to the required directories by copying the following command and running it in a terminal:

flatpak override --user --filesystem=/run/host/var/games/shared/SteamLibrary com.github.Matoking.protontricks

You will need to restart Protontricks for the settings to take effect.
protontricks (WARNING): Steam library folder /run/host/var/games/shared/SteamLibrary not found. Protontricks might not have access to the directory.
Found the following games:
...
```
Now if I override that path using the command given I get this error instead:
```bash
F: Not sharing "/run/host/var/games/shared/SteamLibrary" with sandbox: Path "/run/host" is reserved by Flatpak
```
This is because flatpak has mounted a bunch of it's own stuff in `/run/host` and restricts it's override.

![image](https://github.com/user-attachments/assets/989a5148-ea38-414a-ac65-c5e238eb18e3)

**Comment by Omni-guides** [comment] 2024-12-31 15:42
Fine, but this is all still stemming from you having your Steam library in /run/host which I don't think any distro/anyone else does..

Is the Steam Library not actually just `/var/games/shared/SteamLibrary` ?

**Comment by TheCodeLamp** [comment] 2024-12-31 16:04
I don't **want** to have it on `/run/host` that was what steam chose it as like a year ago when I set up this computer. I made this issue so that people who might be experiencing similar problems to me will know that removing the `/run/host` prefix will solve a lot of issues. After discovering this I have simply edited the `~/.local/share/Steam/steamapps/libraryfolders.vdf` file and made that entry into only `/var/games/shared/SteamLibrary`. Like I said, this has not been a issue up until now, but now that I was made aware of it I have removed the `/run/host` prefix.
I added it back to show the errors that you get if you have it.

**Comment by TheCodeLamp** [comment] 2024-12-31 16:27
I closed this issue when I made it because I wasn't expecting you, or even wanting you, to make any fixes to the script. I know that this issue is rare enough that no one is probably going to experience it again. But if it happens, they might search and find this issue.

**Comment by Omni-guides** [comment] 2024-12-31 18:56
That's fine, and all good. I just wanted to check what the situation was to see if this is something that may come up more often, but for now at least, I don't think it is.

As you say, anyone that hits a similar issue may find this here, and of course if it does become a more regular issue, I can look at handling these paths too.

I'll re-close this ticket for now, thanks!

**Closed by Omni-guides** 2024-12-31 18:56 UTC

**Comment by TheCodeLamp** [comment] 2024-12-31 19:15
Of course, thank you for your wonderful scripts and guides :+1:
